### PR TITLE
Font Optimization

### PR DESCRIPTION
**Pull request by easyuxd**
Credit to @jdlcdl for the recommendation:
https://github.com/marc3linho/OrangeClock/issues/28#issuecomment-1823550484

Used [font_to_py "-c" argument](https://github.com/peterhinch/micropython-font-to-py/blob/master/FONT_TO_PY.md#31-arguments) to compile only the characters currently being used in the UI. Across all 4 fonts, was able to reduce the font sizes from about 280kb to 70kb. This has freed up a significant amount of memory, now >100kb free.

**Note:**
Recompiling orangeClockIcons60 threw off the character size, so I compensated by replacing this with a 56px version (orangeClockIcons56). This required minor adjustments to alignment, included in displayBlockMoscowFees.py.

I'm hoping there are no unforeseen issues with this approach, and others can help test the changes.

### CODE REVIEW

**Comment by marc3linho** [comment]
Either we add the character 'E' 'R' 'O' to the font or we have to change the code. Both acceptable to me. [Line171](https://github.com/marc3linho/OrangeClock/blob/d306785ba7fd2062898dbf983bae41919190267a/src/orangeClockFunctions/displayBlockMoscowFees.py#L171C29-L171C29)  is broken without that change

**Comment by jdlcdl** [comment]
> Either we add the character 'E' 'R' 'O' to the font

Is it the uppercase letters, or lowercase "ero" chars to spell "error"?

**Comment by marc3linho** [comment]
lower case 'e' 'r' 'o' 
capitalization of the chars was my mistake

**Comment by easyuxd** [comment]
Great catch. Recompiled with -c ",1234567890eor "

**Pull request merged**
